# Generated by Django 5.2.7 on 2025-10-31 19:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('provincia', models.CharField(blank=True, max_length=50)),
                ('endereco', models.TextField(blank=True)),
                ('servicos', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contacto', models.CharField(max_length=20)),
                ('ramo', models.CharField(choices=[('Comércio', 'Comércio'), ('Serviços', 'Serviços'), ('Outro', 'Outro')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='gerente_condominio.condominio')),
                ('inquilino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casa', to='gerente_condominio.inquilino')),
            ],
            options={
                'unique_together': {('numero', 'condominio')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('servico', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Concluído', 'Concluído'), ('Em Progresso', 'Em Progresso'), ('Pendente', 'Pendente'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='gerente_condominio.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('duracao_meses', models.IntegerField(choices=[(12, '12 meses'), (24, '24 meses'), (36, '36 meses')])),
                ('valor_renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gerente_condominio.casa')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gerente_condominio.inquilino')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('geral', 'Geral'), ('especifico', 'Específico')], max_length=20)),
                ('tipo_geral', models.CharField(blank=True, choices=[('equipamentos', 'Equipamentos'), ('sistemas', 'Sistemas'), ('estrutura-fisica', 'Estrutura Física')], max_length=20, null=True)),
                ('problema_geral', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_especifico', models.CharField(blank=True, choices=[('hidraulica', 'Hidráulica'), ('eletrica', 'Elétrica'), ('caixilharia', 'Caixilharia')], max_length=20, null=True)),
                ('componente_especifico', models.CharField(blank=True, max_length=50, null=True)),
                ('local_afetado', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField()),
                ('evidencias', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='gerente_condominio.casa')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='gerente_condominio.condominio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='gerente_condominio.empresa')),
            ],
        ),
    ]
