# Generated by Django 5.2.7 on 2025-10-31 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente_condominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='casa',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casas', to='gerente_condominio.condominio'),
        ),
    ]
