# Generated by Django 5.2.7 on 2025-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente_condominio', '0002_alter_casa_unique_together_alter_casa_condominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='valor_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
