# Generated by Django 5.2.7 on 2025-11-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerente_condominio', '0003_contrato_valor_seguro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_seguro',
        ),
    ]
