# Generated by Django 5.2.8 on 2025-11-20 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente_condominio', '0004_remove_contrato_valor_seguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoEspecifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('evidencias', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('hidraulica', 'Hidráulica'), ('eletrica', 'Elétrica'), ('caixilharia', 'Caixilharia')], max_length=20)),
                ('componente', models.CharField(blank=True, max_length=50, null=True)),
                ('local_afetado', models.CharField(blank=True, max_length=200, null=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes_especificas', to='gerente_condominio.casa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manutencoes', to='gerente_condominio.empresa')),
            ],
            options={
                'verbose_name': 'Manutenção Específica',
                'verbose_name_plural': 'Manutenções Específicas',
            },
        ),
        migrations.CreateModel(
            name='ManutencaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('evidencias', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('equipamentos', 'Equipamentos'), ('sistemas', 'Sistemas'), ('estrutura-fisica', 'Estrutura Física')], max_length=20)),
                ('problema', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_manutencoes', to='gerente_condominio.empresa')),
            ],
            options={
                'verbose_name': 'Manutenção Geral',
                'verbose_name_plural': 'Manutenções Gerais',
            },
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
    ]
