# Generated by Django 5.2.8 on 2025-11-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gerente_condominio', '0005_manutencaoespecifica_manutencaogeral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencaoespecifica',
            name='evidencias',
        ),
        migrations.RemoveField(
            model_name='manutencaogeral',
            name='evidencias',
        ),
        migrations.AlterField(
            model_name='manutencaoespecifica',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='manutencaogeral',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='AnexoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='manutencoes_anexos/', verbose_name='Anexo/Evidência')),
                ('object_id', models.PositiveIntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Anexo de Manutenção',
                'verbose_name_plural': 'Anexos de Manutenção',
            },
        ),
    ]
