# Generated by Django 5.2.8 on 2025-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente_condominio', '0006_remove_manutencaoespecifica_evidencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaoespecifica',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='manutencoes_evidencias/', verbose_name='Foto de Evidência'),
        ),
        migrations.AddField(
            model_name='manutencaogeral',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='manutencoes_evidencias/', verbose_name='Foto de Evidência'),
        ),
        migrations.DeleteModel(
            name='AnexoManutencao',
        ),
    ]
