# Generated by Django 5.2.8 on 2025-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente_condominio', '0007_manutencaoespecifica_foto_evidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
